AUGMENTATION:  True
IMAGE_SIZE: [224,224,3] # as per VGG16 
BATCH_SIZE: 16
INCLUDE_TOP: False #whether to include the 3 fully-connected layers at the top of the network
EPOCHS: 5
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.02